server:
  port: 8080

spring:
  application:
    name: cloud-cosumer-order
  cloud:
    zookeeper:
      connect-string: server.wetech.club:2181

#开启feign 对hystrix的支持
feign:
  hystrix:
    enabled: true
