server:
  port: 7003

eureka:
  instance:
    hostname: eureka3.com# eureka 服务端实例名称
  client:
    register-with-eureka: false  # 是否将自己注册至服务中心
    fetch-registry: false # 是否获取服务提供列表
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/,http://eureka1.com:7001/eureka/
